# Generated by Django 5.2.1 on 2025-05-28 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_tickets_created_at_tickets_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='updated_at',
        ),
    ]
